# Generated by Django 5.2.17 on 2026-10-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='average_temperature_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average annual temperature in Celsius', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='climate',
            field=models.CharField(blank=True, help_text='General climate classification', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='gdp_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated city GDP in EUR', max_digits=15, null=True),
        ),
    ]
