# Generated by Django 5.2.17 on 2026-10-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_api', '0002_city_average_temperature_c_city_climate_city_gdp_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='related_cities',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='cities_api.city'),
        ),
    ]
